server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      enabled: true
      routes:
        - id: payment_routh   #路由的id,没有固定规则但是要求唯一,建议配合服务名
          uri: http://localhost:8001 #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka