server:
  port: 8001
spring:
  application:
    name: cloud-provider-hystrix-payment
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.96.130:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useeSSL=false
      username: root
      password: jiaobaba
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

