server:
  port: 80
spring:
  application:
    name: consumer-order-service
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.96.130:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useeSSL=false
      username: root
      password: jiaobaba

eureka:
  client:
    fetch-registry: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka